language: python
matrix:
  include:
    # Django 1.4: Python 2.6--2.7
    - python: "2.7"
      env: DJANGO=django==1.4
    # Django 1.5: Python 2.7, pypy
    #   (As of Django 1.5, Python 2.6 no longer "highly recommended",
    #   and Python 3.2+ support was only "experimental", so skip those.)
    - python: "2.7"
      env: DJANGO=django==1.5
    - python: "pypy"
      env: DJANGO=django==1.5
    # Django 1.6: Python 2.7--3.3, pypy
    - python: "2.7"
      env: DJANGO=django==1.6
    - python: "3.3"
      env: DJANGO=django==1.6
    - python: "pypy"
      env: DJANGO=django==1.6
    # Django 1.7: Python 2.7--3.4, pypy
    - python: "2.7"
      env: DJANGO=django==1.7
    - python: "3.3"
      env: DJANGO=django==1.7
    - python: "3.4"
      env: DJANGO=django==1.7
    - python: "pypy"
      env: DJANGO=django==1.7
    # Django 1.8: "Python 2.7 or above"
    - python: "2.7"
      env: DJANGO=django==1.8
    - python: "3.4"
      env: DJANGO=django==1.8
    - python: "pypy"
      env: DJANGO=django==1.8
before_install:
  - pip install coverage codecov
install:
  - pip install --upgrade setuptools pip
  - pip install -q $DJANGO
  - pip install .
script: coverage run setup.py test
after_success:
  codecov