# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install codecov poetry tox-travis

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov
